# Generated by Django 3.2.4 on 2021-06-06 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=500)),
                ('filed_date', models.DateField()),
                ('closed_date', models.DateField(default=None, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_patient', to=settings.AUTH_USER_MODEL)),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_receptionist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
