# Generated by Django 3.2.4 on 2021-06-06 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_case', to='case.case')),
                ('lab_attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_lab_attendant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
